In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.98246137, 0.89501219, 0.84754466, 0.37507571, 0.1873184 ])

In [14]:
np.random.rand(5,5)

array([[0.15785832, 0.80183242, 0.98727819, 0.65880172, 0.34364317],
       [0.81787486, 0.93490223, 0.80031919, 0.62911856, 0.87832074],
       [0.19889464, 0.42594043, 0.14873176, 0.44072506, 0.43715324],
       [0.51418086, 0.64411949, 0.85246888, 0.30115205, 0.48010553],
       [0.06221196, 0.43898453, 0.65048597, 0.26858731, 0.30745325]])

In [15]:
np.random.randn(2)

array([-1.45849966,  1.10581098])

In [16]:
np.random.randn(20)

array([ 1.07086732,  1.01589956,  0.12794043, -1.85619778,  1.19629267,
       -0.33768426,  1.34939177,  1.4619599 , -0.63143188,  0.11865278,
       -0.85661587, -1.76635866, -0.46929668,  1.00550756, -0.47549831,
        0.12130914,  1.07091546, -1.38030305, -0.06936496, -0.82351966])

In [17]:
np.random.randn(4,4)

array([[ 0.92572674, -1.01353926, -1.82246729,  0.76620145],
       [-0.25687171,  1.34071605, -0.09330762, -0.41632227],
       [-0.14570488, -0.52212501,  0.35957189,  0.15093103],
       [-1.03579247, -1.07077368,  0.84537979,  1.17627625]])

In [18]:
np.random.randint(1,100,10)

array([23,  4,  8, 69, 59,  3, 34, 45, 49, 24])

In [19]:
arr2 = np.arange(25)

In [20]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([34, 30, 39, 42, 21, 29, 18, 33,  1, 41])

In [23]:
arr2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

42

In [25]:
ranarr.min()

1

In [26]:
ranarr.argmax()

3

In [27]:
ranarr.argmin()

8

In [28]:
arr2.shape

(25,)

In [29]:
arr3 = arr2.reshape(5,5)

In [30]:
arr3.shape

(5, 5)

In [31]:
arr3.dtype

dtype('int64')